version: "3.5"
services:
  mysql-work:
    image: mysql:8
    container_name: mysql-work
    restart: always
    networks:
      worknet:
        ipv4_address: ${MYSQL_IP}
    logging: { driver: "json-file", options: { max-size: "10m", max-file: "10" } }
    environment:
      MYSQL_USER: work
      MYSQL_PASSWORD: ${MYSQL_PASSWD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWD}

networks:
  worknet:
    external: true
    name: worknet
